language: go
go:
    - 1.2
before_install:
    - go get github.com/axw/gocov/gocov
    - go get code.google.com/p/go.tools/cmd/cover
    - go get github.com/mattn/goveralls
script:
    - go test -covermode=count -coverprofile=profile.cov
    - $HOME/gopath/bin/goveralls -repotoken nQ6xM1UC8iomu6dXVZ3qDTz9hqRiQqwDW -coverprofile=profile.cov -service=travis-ci
